language: rust
os:
  - linux
rust:
  - stable
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace