language: rust
os:
  - linux
rust:
  - nightly
script:
  - cargo -V
  - rustc -V
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
  - cargo install cargo-supply-chain
  - supply-chain update
  - cargo supply-chain crates
  - cargo supply-chain publishers
  - cargo install --locked cargo-geiger
  - cargo geiger || true
  - cargo install cargo-tree
  - cargo tree
  - cargo install tokei
  - tokei